// The Pinterest feed, rendered from a year of stills scheduled in advance.
//
// A static RSS file cannot drip: Pinterest pins everything in it, up to 200 a day,
// so the whole atlas would go out in eighty days from an account with no followers.
// So the year is written once — pins-data.mjs, generated by
// never-forget-atlas/scripts/publish_feed.py — and this serves only the items whose
// date has arrived. Pinterest sees a feed that grows by itself, about 44 a day,
// from 11 September 2026 to 11 September 2027. Nobody touches it.
//
// What Pinterest reads (help.pinterest.com, "auto-publish Pins from your RSS feed"):
// <title>, <description>, <link> on a claimed domain, and the image from <image>,
// <enclosure> or <media:content>. RSS 2 only, no Atom. The oldest item publishes
// first. neverforget.pics was claimed on 9 September 2026.

import data from "./pins-data.mjs";

// How many due items the feed carries at once. Pinterest pins oldest-first and
// polls within a day, so the feed only needs to hold what it has not reached yet.
// 300 is about a week of the year at 44 a day — room for a missed poll or two
// without re-serving four months of pins every time it asks.
export const WINDOW = 300;

const START = Date.parse(data.start);
const END = Date.parse(data.end);
const MONTHS = ["January", "February", "March", "April", "May", "June", "July",
  "August", "September", "October", "November", "December"];

const escapeXml = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;").replace(/'/g, "&apos;");

// The fabricated date every published name carries, read back as a title. Same
// rule as nf_publish.stills.stamp(): it is not a real date, and presenting it as
// one continues what the site does on every render.
export function stamp(name) {
  const m = /--(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})/.exec(name);
  if (!m) return "";
  return `${Number(m[3])} ${MONTHS[Number(m[2]) - 1]} ${m[1]}, ${m[4]}:${m[5]}`;
}

// When year item i is due. Integer milliseconds, so the last one lands on
// 11 September itself.
export function dueAt(i, count = data.year.length) {
  return START + Math.round(((END - START) * i) / Math.max(count - 1, 1));
}

function item([name, sentenceIdx, tagIdx, length], due) {
  const id = name.split("--")[0];
  const when = stamp(name);
  const title = when ? `${when} · ${id}` : id;
  const text = sentenceIdx.map((i) => data.sentences[i]).join(" ");
  const media = `${data.cdn}/${name.split("-")[0]}/${name}${data.suffix}`;
  const link = `${data.site}/${name}`;
  const tags = tagIdx.map((i) => data.tags[i]);
  return [
    "    <item>",
    `      <title>${escapeXml(title)}</title>`,
    `      <link>${escapeXml(link)}</link>`,
    `      <description>${escapeXml(text)}</description>`,
    `      <guid isPermaLink="false">${escapeXml(name)}</guid>`,
    `      <pubDate>${new Date(due).toUTCString()}</pubDate>`,
    ...tags.map((t) => `      <category>${escapeXml(t)}</category>`),
    `      <enclosure url="${escapeXml(media)}" length="${length}" type="image/jpeg"/>`,
    `      <media:content url="${escapeXml(media)}" medium="image" type="image/jpeg"/>`,
    "    </item>",
  ].join("\n");
}

function document(items, built) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">',
    "  <channel>",
    "    <title>Never Forget</title>",
    `    <link>${escapeXml(data.site)}/</link>`,
    "    <description>POV you're a statistical render</description>",
    `    <lastBuildDate>${new Date(built).toUTCString()}</lastBuildDate>`,
    ...items,
    "  </channel>",
    "</rss>",
    "",
  ].join("\n");
}

// The year, as of `now`: every item that is due, newest WINDOW of them, oldest
// first in the document because that is the order Pinterest publishes in.
export function yearFeed(now = Date.now()) {
  const rows = data.year;
  let due = 0;
  while (due < rows.length && dueAt(due) <= now) due += 1;
  const from = Math.max(0, due - WINDOW);
  const items = [];
  for (let i = from; i < due; i += 1) items.push(item(rows[i], dueAt(i)));
  return { xml: document(items, now), due, total: rows.length };
}

// The test feed: five stills held out of the year, all due at once, so the feed
// can be connected and checked before the year starts. Its images are never in
// the year, so connecting both cannot pin the same one twice.
export function testFeed(now = Date.now()) {
  const items = data.test.map((row, i) => item(row, now - (data.test.length - i) * 60000));
  return { xml: document(items, now), due: items.length, total: items.length };
}

export function response({ xml, due, total }) {
  return {
    statusCode: 200,
    headers: {
      "Content-Type": "application/rss+xml; charset=utf-8",
      // Pinterest polls about daily. An hour of cache costs it nothing and keeps a
      // crawler from rendering the feed on every hit.
      "Cache-Control": "public, max-age=3600",
      "X-Never-Forget-Due": `${due}/${total}`,
    },
    body: xml,
  };
}
